seed: 42

exp:
  root_dir: ./outputs
  exp_name: image_singleview_fista_ours_v18_eval_interval

data:
  root: ./multiview_dataset/fista_singleview_v18_eval_interval
  views: [18]

  input_key: fista_ours_npy
  target_key: ct_gt_npy

  use_view_ratio: true
  full_view: 36

model:
  in_c: 2
  out_c: 1
  stage1_width: 64
  stage2_width: 64
  num_cab: 4

train:
  num_epochs: 200
  batch_size: 2
  num_workers: 0
  pin_memory: true
  amp: true
  grad_clip: 1.0

optimizer:
  lr: 0.0003
  weight_decay: 0.0001

scheduler:
  warmup_epochs: 5
  min_lr: 0.000001

loss:
  lambda_ssim: 0.01
  lambda_stage1: 0.1

early_stopping:
  patience: 40
  mode: max
  min_delta: 0.0001

test:
  batch_size: 2
  num_workers: 0
  pin_memory: true
  max_save_images: 20
  save_npy: true

code_files:
  - ImageDomain_train_multiview.py
  - dataset_code/multiview_image_dataset.py
  - model/Image_Net.py
  - utils/train_utils.py
  - utils/visual_utils.py
